version: "3.8"

services:
  backup:
    build:
      dockerfile: Dockerfile
    image: restic-with-rclone:1.0.0
    env_file:
      - .env  # used to separate sensitive environment variables
    environment:
      - RESTIC_REPOSITORY=rclone:mypcloud:/backup/restic/${RESTIC_HOST}
      - RESTIC_CACHE_DIR=/restic-cache/
    volumes:
      - ./rclone.conf:/root/.config/rclone/rclone.conf
      - restic-cache:/restic-cache
      - /Users:/Users # add at least one volume
    command:
      - /bin/sh
      - -c
      - |
        restic backup --host ${RESTIC_HOST} --verbose /Users/robert/Downloads && restic forget --keep-last 7 --keep-monthly 12 --prune

volumes:
  restic-cache: