version: "3.8"

services:
  restic:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - RESTIC_REPOSITORY=rclone:mypcloud:/backup/restic/s1
      - RESTIC_CACHE_DIR=/restic-cache/
    volumes:
      - ./rclone.conf:/root/.config/rclone/rclone.conf
      - restic-cache:/restic-cache
      - /Users:/Users # add at least one host volume
    command:
      - /bin/sh
      - -c
      - tail -f /dev/null

volumes:
  restic-cache: