version: "3.8"

services:
  backup:
    build:
      dockerfile: Dockerfile
    image: restic-with-rclone:1.0.0
    env_file:
      - .env  # used to separate sensitive environment variables
    environment:
      - RESTIC_REPOSITORY=rclone:mypcloud:/backup/restic/${RESTIC_HOST}
      - RESTIC_CACHE_DIR=/restic-cache/
    volumes:
      - ./rclone.conf:/root/.config/rclone/rclone.conf
      - restic-cache:/restic-cache
      - ./excludes.txt:/excludes.txt
      - ${RESTIC_BACKUP_DIR}:${RESTIC_BACKUP_DIR}
    command:
      - /bin/sh
      - -c
      - |
        echo "# Start Restic-Backup in a Docker container at $(date +'%Y-%m-%d %H:%M')"
        (set -x ; restic backup --host ${RESTIC_HOST} --no-scan --verbose --exclude-file /excludes.txt ${RESTIC_BACKUP_DIR})
        echo "# Start Restic-Forget in a Docker container at $(date +'%Y-%m-%d %H:%M')"
        (set -x ; restic forget --keep-last 7 --keep-monthly 12 --prune)
        echo "# Done at $(date +'%Y-%m-%d %H:%M')"

volumes:
  restic-cache: